//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Admin
{
    public partial class Dashboard
    {
        protected global::System.Web.UI.WebControls.Label PlayersLabel;
        protected global::System.Web.UI.WebControls.Label OnlineLabel;
        protected global::System.Web.UI.WebControls.Label BannedLabel;
        protected global::System.Web.UI.WebControls.Label VipLabel;
        protected global::System.Web.UI.WebControls.Label ItemsLabel;
        protected global::System.Web.UI.WebControls.Label FarmersLabel;
        protected global::System.Web.UI.WebControls.Label StatusLabel;
    }
}
