//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Admin
{
    public partial class PlayerTools
    {
        protected global::System.Web.UI.WebControls.TextBox LookupTextBox;
        protected global::System.Web.UI.WebControls.Button LookupButton;
        protected global::System.Web.UI.WebControls.Label StatusLabel;
        protected global::System.Web.UI.WebControls.Panel PlayerPanel;
        protected global::System.Web.UI.WebControls.Label UserIdLabel;
        protected global::System.Web.UI.WebControls.Label UserNameLabel;
        protected global::System.Web.UI.WebControls.Label NickNameLabel;
        protected global::System.Web.UI.WebControls.Label StateLabel;
        protected global::System.Web.UI.WebControls.TextBox GradeTextBox;
        protected global::System.Web.UI.WebControls.TextBox GpTextBox;
        protected global::System.Web.UI.WebControls.TextBox GoldTextBox;
        protected global::System.Web.UI.WebControls.TextBox MoneyTextBox;
        protected global::System.Web.UI.WebControls.TextBox GiftTokenTextBox;
        protected global::System.Web.UI.WebControls.TextBox BanUntilTextBox;
        protected global::System.Web.UI.WebControls.Button SaveButton;
        protected global::System.Web.UI.WebControls.Button KickButton;
        protected global::System.Web.UI.WebControls.DropDownList BanDaysDropDown;
        protected global::System.Web.UI.WebControls.TextBox BanReasonTextBox;
        protected global::System.Web.UI.WebControls.Button BanButton;
        protected global::System.Web.UI.WebControls.Button UnbanButton;
        protected global::System.Web.UI.WebControls.HiddenField UserIdHidden;
    }
}
