//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Admin
{
    public partial class SetVip
    {
        protected global::System.Web.UI.WebControls.TextBox LookupTextBox;
        protected global::System.Web.UI.WebControls.DropDownList TargetVipDropDown;
        protected global::System.Web.UI.WebControls.DropDownList DurationDropDown;
        protected global::System.Web.UI.WebControls.Button LookupButton;
        protected global::System.Web.UI.WebControls.Button PlusOneButton;
        protected global::System.Web.UI.WebControls.Button ApplyButton;
        protected global::System.Web.UI.WebControls.Button QuickVip10Button;
        protected global::System.Web.UI.WebControls.Button QuickVip15Button;
        protected global::System.Web.UI.WebControls.Button QuickVip20Button;
        protected global::System.Web.UI.WebControls.Label CurrentVipLabel;
        protected global::System.Web.UI.WebControls.Label VipExpLabel;
        protected global::System.Web.UI.WebControls.Label ExpireLabel;
        protected global::System.Web.UI.WebControls.Label StatusLabel;
        protected global::System.Web.UI.WebControls.HiddenField UserIdHidden;
    }
}
